{
 "title": "Sprint 3 dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Медианное предсказание модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, price_app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(price_app_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки запроса",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{handler=\"/api/price/\", instance=\"price_app:8081\", job=\"scrapping-price-app\", method=\"POST\"} / http_request_duration_seconds_count{handler=\"/api/price/\", instance=\"price_app:8081\", job=\"scrapping-price-app\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}